ALTER TABLE matches ADD COLUMN IF NOT EXISTS phase VARCHAR(20) NOT NULL DEFAULT 'POOL';
ALTER TABLE matches ADD COLUMN IF NOT EXISTS penalty_winner VARCHAR(1);
ALTER TABLE matches ADD COLUMN IF NOT EXISTS penalty_score_a INTEGER;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS penalty_score_b INTEGER;
