UPDATE teams SET iso2 = 'za' WHERE name = 'Afrique du Sud';
UPDATE teams SET iso2 = 'dz' WHERE name = 'Algérie';
UPDATE teams SET iso2 = 'de' WHERE name = 'Allemagne';
UPDATE teams SET iso2 = 'gb-eng' WHERE name = 'Angleterre';
UPDATE teams SET iso2 = 'sa' WHERE name = 'Arabie Saoudite';
UPDATE teams SET iso2 = 'ar' WHERE name = 'Argentine';
UPDATE teams SET iso2 = 'au' WHERE name = 'Australie';
UPDATE teams SET iso2 = 'at' WHERE name = 'Autriche';
UPDATE teams SET iso2 = 'be' WHERE name = 'Belgique';
UPDATE teams SET iso2 = 'ba' WHERE name = 'Bosnie-Herzégovine';
UPDATE teams SET iso2 = 'br' WHERE name = 'Brésil';
UPDATE teams SET iso2 = 'ca' WHERE name = 'Canada';
UPDATE teams SET iso2 = 'cv' WHERE name = 'Cap-Vert';
UPDATE teams SET iso2 = 'co' WHERE name = 'Colombie';
UPDATE teams SET iso2 = 'kr' WHERE name = 'Corée du Sud';
UPDATE teams SET iso2 = 'ci' WHERE name = 'Côte d''Ivoire';
UPDATE teams SET iso2 = 'hr' WHERE name = 'Croatie';
UPDATE teams SET iso2 = 'cw' WHERE name = 'Curaçao';
UPDATE teams SET iso2 = 'gb-sct' WHERE name = 'Écosse';
UPDATE teams SET iso2 = 'eg' WHERE name = 'Égypte';
UPDATE teams SET iso2 = 'ec' WHERE name = 'Équateur';
UPDATE teams SET iso2 = 'es' WHERE name = 'Espagne';
UPDATE teams SET iso2 = 'us' WHERE name = 'États-Unis';
UPDATE teams SET iso2 = 'fr' WHERE name = 'France';
UPDATE teams SET iso2 = 'gh' WHERE name = 'Ghana';
UPDATE teams SET iso2 = 'ht' WHERE name = 'Haïti';
UPDATE teams SET iso2 = 'iq' WHERE name = 'Irak';
UPDATE teams SET iso2 = 'ir' WHERE name = 'Iran';
UPDATE teams SET iso2 = 'jp' WHERE name = 'Japon';
UPDATE teams SET iso2 = 'jo' WHERE name = 'Jordanie';
UPDATE teams SET iso2 = 'ma' WHERE name = 'Maroc';
UPDATE teams SET iso2 = 'mx' WHERE name = 'Mexique';
UPDATE teams SET iso2 = 'no' WHERE name = 'Norvège';
UPDATE teams SET iso2 = 'nz' WHERE name = 'Nouvelle-Zélande';
UPDATE teams SET iso2 = 'uz' WHERE name = 'Ouzbékistan';
UPDATE teams SET iso2 = 'pa' WHERE name = 'Panama';
UPDATE teams SET iso2 = 'py' WHERE name = 'Paraguay';
UPDATE teams SET iso2 = 'nl' WHERE name = 'Pays-Bas';
UPDATE teams SET iso2 = 'pt' WHERE name = 'Portugal';
UPDATE teams SET iso2 = 'qa' WHERE name = 'Qatar';
UPDATE teams SET iso2 = 'cd' WHERE name = 'RD Congo';
UPDATE teams SET iso2 = 'cz' WHERE name = 'République Tchèque';
UPDATE teams SET iso2 = 'sn' WHERE name = 'Sénégal';
UPDATE teams SET iso2 = 'se' WHERE name = 'Suède';
UPDATE teams SET iso2 = 'ch' WHERE name = 'Suisse';
UPDATE teams SET iso2 = 'tn' WHERE name = 'Tunisie';
UPDATE teams SET iso2 = 'tr' WHERE name = 'Turquie';
UPDATE teams SET iso2 = 'uy' WHERE name = 'Uruguay';
