import { describe, it, expect } from "vitest";
import { buildMigration, slugify } from "../migrate/bundle.js";
import type { ScanResult, McpServer, Integration, Hook, ContextFile } from "../types.js";

const GENERATED_AT = "2026-01-01T00:00:00.000Z";
const OPTIONS = { targetDir: "/home/tester/.mistral", generatedAt: GENERATED_AT };

function mcp(overrides: Partial<McpServer> = {}): McpServer {
  return {
    name: "github",
    source: ".mcp.json",
    type: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-github"],
    envVars: [],
    commandAvailable: true,
    status: "ok",
    diagnostics: [],
    ...overrides,
  };
}

function integration(overrides: Partial<Integration> = {}): Integration {
  return {
    name: "MemPalace",
    description: "Memory layer",
    detected: true,
    status: "ok",
    diagnostics: [],
    ...overrides,
  };
}

function hook(overrides: Partial<Hook> = {}): Hook {
  return {
    event: "PreToolUse",
    matcher: "Bash",
    type: "command",
    command: "./guard.sh",
    source: ".claude/settings.json",
    scriptExists: true,
    status: "ok",
    diagnostics: [],
    ...overrides,
  };
}

function contextFile(overrides: Partial<ContextFile> = {}): ContextFile {
  return {
    path: "./CLAUDE.md",
    exists: true,
    sizeBytes: 2048,
    estimatedTokens: 512,
    scope: "project",
    status: "ok",
    ...overrides,
  };
}

function scan(overrides: Partial<ScanResult> = {}): ScanResult {
  return {
    projectPath: "/home/tester/project",
    model: { configured: null, source: null, isSonnet: false, status: "warning", diagnostics: [] },
    mcpServers: [],
    contextFiles: [],
    hooks: [],
    integrations: [],
    envVarSummary: { total: 0, set: 0, missing: 0, missingList: [], setList: [] },
    ...overrides,
  };
}

function fileNamed(migration: ReturnType<typeof buildMigration>, name: string): string {
  const file = migration.files.find((f) => f.name === name);
  expect(file, `expected file ${name}`).toBeDefined();
  return file!.content;
}

// --- slugify ---

describe("slugify", () => {
  it("lowercases and dashes a display name", () => {
    expect(slugify("RTK (Rust Token Killer)")).toBe("rtk-rust-token-killer");
  });

  it("strips leading and trailing separators", () => {
    expect(slugify("  Caveman!  ")).toBe("caveman");
  });

  it("falls back to a placeholder for a name with no usable characters", () => {
    expect(slugify("***")).toBe("unnamed");
  });
});

// --- file set ---

describe("buildMigration file set", () => {
  it("always emits the four Mistral files", () => {
    const migration = buildMigration(scan(), OPTIONS);
    expect(migration.files.map((f) => f.name)).toEqual([
      "config.yaml",
      "mcps.yaml",
      "skills.yaml",
      "migration_report.yaml",
    ]);
  });

  it("emits empty maps rather than omitting sections on an empty environment", () => {
    const migration = buildMigration(scan(), OPTIONS);
    expect(fileNamed(migration, "mcps.yaml")).toContain("mcps: {}");
    expect(fileNamed(migration, "skills.yaml")).toContain("skills: {}");
    expect(migration.stats).toEqual({ mcpServers: 0, skills: 0, contextFiles: 0 });
  });

  it("stamps provenance headers on every file", () => {
    const migration = buildMigration(scan(), OPTIONS);
    for (const file of migration.files) {
      expect(file.content).toContain("# Generated by ai-env-manager migrate");
      expect(file.content).toContain(`# Generated at: ${GENERATED_AT}`);
    }
  });
});

// --- MCP servers ---

describe("buildMigration MCP servers", () => {
  it("migrates a stdio server with its command and args", () => {
    const migration = buildMigration(scan({ mcpServers: [mcp()] }), OPTIONS);
    const yaml = fileNamed(migration, "mcps.yaml");
    expect(yaml).toContain("github:");
    expect(yaml).toContain("transport: stdio");
    expect(yaml).toContain("command: npx");
    expect(yaml).toContain("- \"@modelcontextprotocol/server-github\"");
    expect(migration.stats.mcpServers).toBe(1);
  });

  it("migrates an SSE server with its url", () => {
    const server = mcp({ name: "remote", type: "sse", command: undefined, args: undefined, url: "https://example.test/sse" });
    const yaml = fileNamed(buildMigration(scan({ mcpServers: [server] }), OPTIONS), "mcps.yaml");
    expect(yaml).toContain("transport: sse");
    expect(yaml).toContain('url: "https://example.test/sse"');
    expect(yaml).not.toContain("command:");
  });

  it("emits env vars as placeholders and never their values", () => {
    const server = mcp({ envVars: [{ name: "GITHUB_TOKEN", isSet: true, isApiKey: true }] });
    const yaml = fileNamed(buildMigration(scan({ mcpServers: [server] }), OPTIONS), "mcps.yaml");
    expect(yaml).toContain('GITHUB_TOKEN: "${GITHUB_TOKEN}"');
  });

  it("flags an unset env var for review", () => {
    const server = mcp({ envVars: [{ name: "GITHUB_TOKEN", isSet: false, isApiKey: true }] });
    const migration = buildMigration(scan({ mcpServers: [server] }), OPTIONS);
    expect(migration.needsReview.some((n) => n.includes("GITHUB_TOKEN"))).toBe(true);
  });

  it("migrates a broken server but flags it for review", () => {
    const server = mcp({ status: "error", diagnostics: ["Command 'npx' not found in PATH"] });
    const migration = buildMigration(scan({ mcpServers: [server] }), OPTIONS);
    expect(migration.stats.mcpServers).toBe(1);
    expect(migration.needsReview.some((n) => n.includes("is broken in Claude Code"))).toBe(true);
  });

  it("keeps both servers when two sources declare the same name", () => {
    const migration = buildMigration(
      scan({ mcpServers: [mcp(), mcp({ source: "~/.claude/settings.json" })] }),
      OPTIONS
    );
    expect(migration.stats.mcpServers).toBe(2);
    const yaml = fileNamed(migration, "mcps.yaml");
    expect(yaml).toContain("github:");
    expect(yaml).toContain("github-2:");
  });
});

// --- skills, context, hooks ---

describe("buildMigration skills, context and hooks", () => {
  it("migrates only detected integrations", () => {
    const migration = buildMigration(
      scan({ integrations: [integration(), integration({ name: "Caveman", detected: false })] }),
      OPTIONS
    );
    const yaml = fileNamed(migration, "skills.yaml");
    expect(yaml).toContain("mempalace:");
    expect(yaml).not.toContain("caveman:");
    expect(migration.stats.skills).toBe(1);
  });

  it("keeps only context files that exist", () => {
    const migration = buildMigration(
      scan({ contextFiles: [contextFile(), contextFile({ path: "~/.claude/CLAUDE.md", exists: false })] }),
      OPTIONS
    );
    expect(migration.stats.contextFiles).toBe(1);
    expect(fileNamed(migration, "config.yaml")).toContain('path: "./CLAUDE.md"');
  });

  it("records hooks as not migrated instead of dropping them silently", () => {
    const migration = buildMigration(scan({ hooks: [hook()] }), OPTIONS);
    expect(migration.notMigrated).toHaveLength(1);
    expect(migration.notMigrated[0].item).toBe("hook PreToolUse (Bash)");
    expect(fileNamed(migration, "migration_report.yaml")).toContain("hooks_not_migrated: 1");
  });

  it("flags a configured Anthropic model for review and leaves the Mistral model unset", () => {
    const migration = buildMigration(
      scan({ model: { configured: "sonnet", source: ".claude/settings.json", isSonnet: true, status: "ok", diagnostics: [] } }),
      OPTIONS
    );
    expect(migration.needsReview.some((n) => n.includes("pick a Mistral model"))).toBe(true);
    expect(fileNamed(migration, "config.yaml")).toContain("mistral_model: null");
  });
});

// --- report ---

describe("buildMigration report", () => {
  it("summarises the statistics of a populated environment", () => {
    const migration = buildMigration(
      scan({
        mcpServers: [mcp()],
        integrations: [integration()],
        contextFiles: [contextFile()],
        hooks: [hook()],
      }),
      OPTIONS
    );
    const report = fileNamed(migration, "migration_report.yaml");
    expect(report).toContain("mcp_servers: 1");
    expect(report).toContain("skills: 1");
    expect(report).toContain("context_files: 1");
    expect(report).toContain(`target_dir: "${OPTIONS.targetDir}"`);
  });

  it("lists every generated file including itself", () => {
    const report = fileNamed(buildMigration(scan(), OPTIONS), "migration_report.yaml");
    expect(report).toContain("- config.yaml");
    expect(report).toContain("- migration_report.yaml");
  });
});
