package com.pronocore.dto.request;

public enum EmailType {
    VERIFICATION,
    PASSWORD_RESET,
    MATCH_REMINDER,
    RACE_REMINDER,
    GAGE_RESOLUTION,
    GROUP_NEW_MATCHES,
    GROUP_NEW_RACES,
    GROUP_MEMBERSHIP_REQUEST,
    TEST_CEDRIC
}
