const ISO2: Record<string, string> = {
  'Afrique du Sud': 'za',
  'Algérie': 'dz',
  'Allemagne': 'de',
  'Angleterre': 'gb-eng',
  'Arabie Saoudite': 'sa',
  'Argentine': 'ar',
  'Australie': 'au',
  'Autriche': 'at',
  'Belgique': 'be',
  'Bosnie-Herzégovine': 'ba',
  'Brésil': 'br',
  'Canada': 'ca',
  'Cap-Vert': 'cv',
  'Colombie': 'co',
  'Corée du Sud': 'kr',
  "Côte d'Ivoire": 'ci',
  'Croatie': 'hr',
  'Curaçao': 'cw',
  'Écosse': 'gb-sct',
  'Égypte': 'eg',
  'Équateur': 'ec',
  'Espagne': 'es',
  'États-Unis': 'us',
  'France': 'fr',
  'Ghana': 'gh',
  'Haïti': 'ht',
  'Irak': 'iq',
  'Iran': 'ir',
  'Japon': 'jp',
  'Jordanie': 'jo',
  'Maroc': 'ma',
  'Mexique': 'mx',
  'Norvège': 'no',
  'Nouvelle-Zélande': 'nz',
  'Ouzbékistan': 'uz',
  'Panama': 'pa',
  'Paraguay': 'py',
  'Pays-Bas': 'nl',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'RD Congo': 'cd',
  'République Tchèque': 'cz',
  'Sénégal': 'sn',
  'Suède': 'se',
  'Suisse': 'ch',
  'Tunisie': 'tn',
  'Turquie': 'tr',
  'Uruguay': 'uy',
};

export const getFlagUrl = (teamName: string): string | null => {
  const code = ISO2[teamName];
  return code ? `https://flagcdn.com/${code}.svg` : null;
};
