const FLAGS: Record<string, string> = {
  'Afrique du Sud': '🇿🇦',
  'Algérie': '🇩🇿',
  'Allemagne': '🇩🇪',
  'Angleterre': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Arabie Saoudite': '🇸🇦',
  'Argentine': '🇦🇷',
  'Australie': '🇦🇺',
  'Autriche': '🇦🇹',
  'Belgique': '🇧🇪',
  'Bosnie-Herzégovine': '🇧🇦',
  'Brésil': '🇧🇷',
  'Canada': '🇨🇦',
  'Cap-Vert': '🇨🇻',
  'Colombie': '🇨🇴',
  'Corée du Sud': '🇰🇷',
  "Côte d'Ivoire": '🇨🇮',
  'Croatie': '🇭🇷',
  'Curaçao': '🇨🇼',
  'Écosse': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Égypte': '🇪🇬',
  'Équateur': '🇪🇨',
  'Espagne': '🇪🇸',
  'États-Unis': '🇺🇸',
  'France': '🇫🇷',
  'Ghana': '🇬🇭',
  'Haïti': '🇭🇹',
  'Irak': '🇮🇶',
  'Iran': '🇮🇷',
  'Japon': '🇯🇵',
  'Jordanie': '🇯🇴',
  'Maroc': '🇲🇦',
  'Mexique': '🇲🇽',
  'Norvège': '🇳🇴',
  'Nouvelle-Zélande': '🇳🇿',
  'Ouzbékistan': '🇺🇿',
  'Panama': '🇵🇦',
  'Paraguay': '🇵🇾',
  'Pays-Bas': '🇳🇱',
  'Portugal': '🇵🇹',
  'Qatar': '🇶🇦',
  'RD Congo': '🇨🇩',
  'République Tchèque': '🇨🇿',
  'Sénégal': '🇸🇳',
  'Suède': '🇸🇪',
  'Suisse': '🇨🇭',
  'Tunisie': '🇹🇳',
  'Turquie': '🇹🇷',
  'Uruguay': '🇺🇾',
};

export const getFlag = (teamName: string): string => FLAGS[teamName] ?? '🏳️';
